version: '3.8'

services:
  db:
    restart: always
    container_name: cloud_postgres_app
    image: postgres:${DB_TAG}
    ports:
      - ${DB_PORT_IN}:${DB_PORT_OUT}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME_DB}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  web:
    restart: always
    container_name: cloud_web_app
    build:
      context: ../
      dockerfile: _CI/Dockerfile
      args:
        - HTTP_PROXY=${HTTP_PROXY}
    ports:
      - ${API_PORT_IN}:${API_PORT_OUT}
    volumes:
      - logs_data:/app/logs
    depends_on:
      - db
    command: ./entrypoint.sh

volumes:
  postgres_data:
  logs_data:
